#some constant for AMT app
SAMPLE_RATE = 22050
FFT_SIZE = 4096
WINDOW_SIZE = 7

HOP_LENGTH = 512
WIN_LENGTH = 400
MIN_LEVEL_DB = -100.0
REF_LEVEL_DB = 20.0

DEFAULT_BPM = 120

IMG_WIDTH = 224
IMG_HEIGHT = 224
NUM_CHANNELS = 3

MIN_MIDI_TONE = 21
MAX_MIDI_TONE = 108
NOTE_RANGE = MAX_MIDI_TONE - MIN_MIDI_TONE + 1
ALL_MIDI_TONES = 128

BIN_MULTIPLE = 4
BIN_PER_OCTAVE = 12 * BIN_MULTIPLE
N_BINS = NOTE_RANGE * BIN_MULTIPLE

INPUT_SHAPE = (WINDOW_SIZE, NOTE_RANGE * BIN_MULTIPLE)
INPUT_SHAPE_CHANNEL = (WINDOW_SIZE, NOTE_RANGE * BIN_MULTIPLE, 1)

MIDI_DIR = './datasets/data/midi/'
WAV_DIR = './datasets/data/wav/'
SPECS_DIR = './datasets/data/spectrograms/'

MODELS_DIR = './models/'

SOUNDFONT = "./utils/FluidR3_GM2-2.SF2"
